name: Python Secrets Management

on:
  push:

jobs:
  deploy_with_secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie kodu repozytorium
        uses: actions/checkout@v4

      - name: Symulacja wdrożenia z użyciem sekretu API_KEY
        env:
          MY_API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Rozpoczynam proces autoryzacji i wdrażania..."
          # GitHub automatycznie maskuje sekrety, zamieniając je na *** w logach
          echo "Używany klucz API: $MY_API_KEY"
          echo "🚀 Wdrożenie zakończone pomyślnie!"