name: Run Custom Action

on:
  push:
    branches: [ main ]

jobs:
  test_with_custom_action:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie kodu repozytorium
        uses: actions/checkout@v4

      - name: Uruchomienie własnej akcji (Custom Action)
        uses: ./.github/actions/my-action
        with:
          python-version: "3.11"